defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.pretrain.train_diffusion_agent.TrainDiffusionAgent

name: pusht_pre_diffusion_mlp_ta${horizon_steps}_td${denoising_steps}
logdir: ${oc.env:DPPO_LOG_DIR}/pusht-pretrain/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
train_dataset_path: ${oc.env:DPPO_DATA_DIR}/pusht/train.npz

seed: 42
device: cuda:0
env: pusht
obs_dim: 5  # agent_x, agent_y, block_x, block_y, block_angle
action_dim: 2  # target_agent_x, target_agent_y
denoising_steps: 20
horizon_steps: 16  # Diffusion Policy paper uses 16 for Push-T
cond_steps: 2  # condition on 2 observation steps

wandb:
  entity: ${oc.env:DPPO_WANDB_ENTITY}
  project: pusht-pretrain
  run: ${now:%H-%M-%S}_${name}

train:
  n_epochs: 3000  # Match robomimic - much more training!
  batch_size: 256
  learning_rate: 1e-4
  weight_decay: 1e-6
  lr_scheduler:
    first_cycle_steps: 3000
    warmup_steps: 100
    min_lr: 1e-5
  save_model_freq: 500

model:
  _target_: model.diffusion.diffusion.DiffusionModel
  predict_epsilon: True
  denoised_clip_value: 1.0
  network:
    _target_: model.diffusion.mlp_diffusion.DiffusionMLP
    horizon_steps: ${horizon_steps}
    action_dim: ${action_dim}
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    time_dim: 16
    mlp_dims: [512, 512, 512]  # Larger network to match other configs
    activation_type: ReLU
    out_activation_type: Identity
    use_layernorm: False
    residual_style: True
  horizon_steps: ${horizon_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  denoising_steps: ${denoising_steps}
  device: ${device}

ema:
  decay: 0.995

train_dataset:
  _target_: agent.dataset.sequence.StitchedSequenceDataset
  dataset_path: ${train_dataset_path}
  horizon_steps: ${horizon_steps}
  cond_steps: ${cond_steps}
  device: ${device}
