defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.finetune.train_idql_diffusion_agent.TrainIDQLDiffusionAgent

name: ${env_name}_idql_diffusion_mlp_ta${horizon_steps}_td${denoising_steps}
logdir: ${oc.env:DPPO_LOG_DIR}/robomimic-finetune/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
base_policy_path: ${oc.env:DPPO_LOG_DIR}/robomimic-pretrain/transport/transport_pre_diffusion_mlp_ta8_td20/2024-07-08_11-18-59/checkpoint/state_8000.pt
robomimic_env_cfg_path: cfg/robomimic/env_meta/${env_name}.json
normalization_path: ${oc.env:DPPO_DATA_DIR}/robomimic/${env_name}/normalization.npz

seed: 42
device: cuda:0
env_name: transport
obs_dim: 59
action_dim: 14
denoising_steps: 20
cond_steps: 1
horizon_steps: 8
act_steps: 8

env:
  n_envs: 50
  name: ${env_name}
  best_reward_threshold_for_success: 1
  max_episode_steps: 800
  save_video: False
  wrappers:
    robomimic_lowdim:
      normalization_path: ${normalization_path}
      low_dim_keys: ['robot0_eef_pos',
                    'robot0_eef_quat',
                    'robot0_gripper_qpos',
                    "robot1_eef_pos",
                    "robot1_eef_quat",
                    "robot1_gripper_qpos",
                    'object'] # same order of preprocessed observations
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: True

wandb:
  entity: ${oc.env:DPPO_WANDB_ENTITY}
  project: robomimic-${env_name}-finetune
  run: ${now:%H-%M-%S}_${name}

train:
  n_train_itr: 201
  n_critic_warmup_itr: 5
  n_steps: 400
  gamma: 0.999
  actor_lr: 1e-5
  actor_weight_decay: 0
  actor_lr_scheduler:
    first_cycle_steps: 1000
    warmup_steps: 10
    min_lr: 1e-5
  critic_lr: 1e-3
  critic_weight_decay: 0
  critic_lr_scheduler:
    first_cycle_steps: 1000
    warmup_steps: 10
    min_lr: 1e-3
  save_model_freq: 100
  val_freq: 10
  render:
    freq: 1
    num: 0
  # IDQL specific
  scale_reward_factor: 1
  eval_deterministic: True
  eval_sample_num: 10 # how many samples to score during eval
  critic_tau: 0.001  # rate of target q network update
  use_expectile_exploration: True
  buffer_size: 5000 # * n_envs
  replay_ratio: 128
  batch_size: 1000
  diagnostic:
    enabled: true
    env_idx: 0
    bc_num_samples: 8
  # Support filtering - filters diffusion candidates by support distance before Q-selection
  # This prevents selecting "outlier" actions that have high Q but are far from BC support
  support_filter:
    enabled: true
    mode: "pairwise"  # "pairwise" (cheap, inter-candidate distance) or "bc" (sample from frozen BC)
    bc_num_samples: 32  # Only used when mode="bc"
    act_steps: ${act_steps}  # Use act_steps for distance computation (null = use all horizon_steps)
    # Annealing by iteration: start strict, loosen over time
    # Format: list of [itr_threshold, topk_value] pairs
    # topk_value can be int, float (fraction of S), or string like "S/4"
    topk_schedule:
      - [0, 3]      # itr 0-49: keep top 3 by support (strict)
      - [50, 3]     # itr 50-99: keep top 5 by support
      - [100, 3]    # itr 100+: keep top 8 (mild filtering)
      - [150, 5]   # itr 150+: keep all 10 (no filtering)
    # Alternative: anneal by success rate (set anneal_by_success: true to use)
    anneal_by_success: false
    success_thresholds:
      - [0.0, 3]    # success < 10%: strict filtering
      - [0.1, 5]    # success 10-30%: moderate  
      - [0.3, 8]    # success 30-50%: mild
      - [0.5, 10]   # success > 50%: no filtering

model:
  _target_: model.diffusion.diffusion_idql.IDQLDiffusion
  # Sampling HPs
  min_sampling_denoising_std: 0.1
  randn_clip_value: 3
  #
  network_path: ${base_policy_path}
  actor:
    _target_: model.diffusion.mlp_diffusion.DiffusionMLP
    time_dim: 32
    mlp_dims: [1024, 1024, 1024]
    residual_style: True
    use_layernorm: True  # Helps reduce outliers in diffusion samples (recommended by IDQL paper)
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    horizon_steps: ${horizon_steps}
    action_dim: ${action_dim}
  critic_q:
    _target_: model.common.critic.CriticObsAct
    action_dim: ${action_dim}
    action_steps: ${act_steps}
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    mlp_dims: [256, 256, 256]
    activation_type: Mish
    residual_style: True
  critic_v:
    _target_: model.common.critic.CriticObs
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    mlp_dims: [256, 256, 256]
    activation_type: Mish
    residual_style: True
  horizon_steps: ${horizon_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  denoising_steps: ${denoising_steps}
  device: ${device}