defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.eval.eval_diffusion_agent.EvalDiffusionAgent

name: pusht_eval_diffusion_mlp
logdir: ${oc.env:DPPO_LOG_DIR}/pusht-eval/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
checkpoint_path: ${oc.env:DPPO_LOG_DIR}/pusht-finetune/REPLACE_WITH_MODEL_PATH/checkpoint/state_500.pt
normalization_path: ${oc.env:DPPO_DATA_DIR}/pusht/normalization.npz

seed: 42
device: cuda:0
env_name: pusht
obs_dim: 5
action_dim: 2
denoising_steps: 20
cond_steps: 2
horizon_steps: 8
act_steps: 8

env:
  n_envs: 10
  name: ${env_name}
  env_type: pusht
  max_episode_steps: 300
  save_video: True
  wrappers:
    pusht_lowdim:
      normalization_path: ${normalization_path}
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: False

eval:
  n_episodes: 50
  render: True
  deterministic: True

